apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb-rc
spec:
  replicas: 3
  selector:
    env: prod
  template:
    metadata:
      name: myweb-pod
      labels:
        env: prod
      spec:
        containers:
        - name: myweb-con
          image: httpd